apiVersion: apps/v1
kind: Deployment
metadata:
  name: vtok
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vtok
  template:
    metadata:
      labels:
        app: vtok
    spec:
      containers:
      - image: okteto.dev/vtok:latest
        name: vtok
        ports:
        - containerPort: 8080
